blueprint:
  name: Motion or Door Security Notification (Conditional)
  description: >
    Sends a notification to a mobile device when a motion sensor or door is triggered, 
    but optionally only if a specific condition is met (e.g., no one is home).
  domain: automation
  input:
    motion_sensor:
      name: Motion Sensor
      description: The motion sensor to monitor.
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
    door_sensor:
      name: Door Sensor
      description: The door/contact sensor to monitor.
      selector:
        entity:
          domain: binary_sensor
          device_class: door
    notify_device:
      name: Device to Notify
      description: The mobile device that will receive the notification.
      selector:
        device:
          integration: mobile_app
    optional_condition_entity:
      name: (Optional) Condition Entity
      description: >
        Select an entity to check before sending the notification. 
        Example: Select your 'Person' entity or a 'Group' of people.
      default: []
      selector:
        entity: {}
    optional_condition_state:
      name: (Optional) Required State
      description: >
        The state the entity above must be in to allow the notification. 
        Example: 'not_home' (for people) or 'on' (for a security switch).
      default: "not_home"
    custom_message:
      name: Notification Message
      description: The text to send. Use {{ trigger.to_state.name }} to insert the sensor name dynamically.
      default: "Security Alert: {{ trigger.to_state.name }} has been triggered."

trigger:
  - platform: state
    entity_id: !input motion_sensor
    from: "off"
    to: "on"
  - platform: state
    entity_id: !input door_sensor
    from: "off"
    to: "on"

condition:
  - condition: template
    value_template: >
      {% set entity = input_optional_condition_entity %}
      {% set required_state = input_optional_condition_state %}
      {% if entity %}
        {{ states(entity) == required_state }}
      {% else %}
        {{ true }}
      {% endif %}

action:
  - domain: mobile_app
    type: notify
    device_id: !input notify_device
    message: !input custom_message
    title: "Home Security"

# Mapping inputs to variables for the condition template
variables:
  input_optional_condition_entity: !input optional_condition_entity
  input_optional_condition_state: !input optional_condition_state
